name: "Vercel Deployment"
author: "Zhiyuan Zheng"
description: "Deploy static build to Vercel"
branding:
  icon: "package"
  color: "white"

inputs:
  vercelToken:
    description: "Your token at Vercel. See https://vercel.com/account/tokens"
    required: true
  vercelOrgId:
    description: "Your Organization ID at Vercel."
    required: true
  vercelProjectId:
    description: "Your Project ID at Vercel."
    required: true
  githubToken:
    description: "Your token at GitHub. See https://github.com/settings/tokens"
    required: true
  buildOption:
    default: false
  buildSource:
    description: "Your source code to build."
    default: ""
  deploySource:
    description: "Your source code to deploy."
    default: ""
  assignDomain:
    description: "You can assign a domain to this deployment. Please note that this domain must have been configured in the project."

runs:
  using: "node12"
  main: "src/index.js"
