name: "Vercel Deployment"
author: "Zhiyuan Zheng"
description: "Deploy static build to Vercel"
branding:
  icon: "package"
  color: "white"

inputs:
  vercelToken:
    description: "Your token at Vercel. See https://vercel.com/account/tokens"
    required: true
  vercelOrgId:
    description: "Your Organization ID at Vercel."
    required: true
  vercelProjectId:
    description: "Your Project ID at Vercel."
    required: true
  githubToken:
    description: "Your token at GitHub. See https://github.com/settings/tokens"
    required: true
  buildOption:
    description: "If your site requires building. Like `npm run build`."
    default: false
  buildSource:
    description: "If your site requires building. Like `examples/nextjs`."
    default: ""
  buildOutput:
    description: "If your site requires building. Provide the build output folder in the format of `FOLDER-NAME`. Like `public` for Gatsby or `out` for Next.js"
    default: ""
  buildDomain:
    description: "You can assign a domain to this deployment. Please note that this domain must have been configured in the project."

runs:
  using: "node12"
  main: "src/index.js"
